# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
# pipeline: supervised_embeddings
pipeline:
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
    return_sequence: true
  - name: "ResponseSelector"
    retrieval_intent: chitchat
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "SklearnIntentClassifier"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
    max_history: 4
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FormPolicy
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.35
    ambiguity_threshold: 0.1
    core_threshold: 0.35
    fallback_nlu_action_name: "action_default_fallback"
    fallback_core_action_name: "action_default_fallback"
    deny_suggestion_intent_name: "chitchat"
